### ISSUE TITLE
Problems building for musl + vendored OpenSSL

### ISSUE THREAD

**Issue by pythoneer** [panicbit/fcm-rust#10]
Hi, i recently stumbled upon a problem by trying to deploy my server with the push functionality provided by your crate. 

I tried to recreate the problem in [this repository](https://github.com/pythoneer/fcm_musl_test) that is based on your example and indeed its behaving the same as my original server (that i cannot share in the public)

For my deployment i try to use a scratch docker image and i want to link everything statically. That's the reason i try to build it with musl and link OpenSSL statically (at least i try to do that)

when i build the example (and my real sever) with 
```
cargo build --release
```
on my arch linux dev machine everything works fine. But when i try to use musl and static OpenSSL with

```
cargo build --target x86_64-unknown-linux-musl --features vendored --release
```

it is not working anymore. The only thing i get is
```
Error: ServerError(None)
```

I assume it has something todo with OpenSSL but i don't really know if i can get any more information from the fcm crate. I am not really sure if this is helpful but i also use the a2 crate (looks like it is somehow related and Julius is also a contributor and author) and it works without problems with this setup. fcm + a2 works on my developer machine but as soon as i choose the musl target and use static OpenSSL only fcm is not working anymore on my machine and inside my docker image.

EDIT:
Ok i tested a little bit further and it looks like that linking to musl is unrelated. Just trying to statically link OpenSSL makes the difference by itself. So using

```
cargo build --features vendored --release 
```
is recreating the problem. I have to admit that i don't really know exactly what i am doing here, but from what i read in the openssl crate documentation i hope this is not absolutely wrong. 

(just copy the cargo toml from the test repo mentioned above)
```
[dependencies]
argparse = "0.2.1"
tokio = "0.1"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
fcm = "0.4"
futures = "0.1"
openssl-sys = { version = "0.9.35", feature = ["vendored"] }

[features]
vendored = ["openssl-sys/vendored"]
```

**Comment by panicbit** [comment]
Unfortunately I cannot reproduce the issue on my own system :disappointed: . I'm only getting `Error: Unauthorized` which should be fine.
I'll try to compile it with musl and on a different system in a few hours.

**Comment by pythoneer** [comment]
i only get Unauthorized if the api key and device token is wrong ... oh sorry i should have mentioned somewhere .. the resulting application needs some arguments just like the example `--api_key` with a valid fcm api key and `--device_token` with a valid android device token to push to

**Comment by panicbit** [comment]
Have a look at this https://github.com/sfackler/rust-openssl/issues/829

**Comment by panicbit** [comment]
It seems like the solution is to call [`openssl_probe::init_ssl_cert_env_vars()`](https://docs.rs/openssl-probe/0.1.2/openssl_probe/fn.init_ssl_cert_env_vars.html)

**Comment by pythoneer** [comment]
Wow! The first test looks like its working! I really appreciate your help, may i let a ❤ for you here to pick up? :D 

I think i can close this now. I think i need some time to incorporate this to the actual project but i am confident that this was the real reason.

[closed]

**Comment by panicbit** [comment]
It's woth mentioning that - despite what the referenced issue says - cargo does not use openssl_probe directly. So maybe there are other ways to do it. :heart:
