### ISSUE TITLE
Backport multi message to stable

### ISSUE THREAD

**Issue by SnowyCoder** [panicbit/fcm-rust#18]
Hello, the 0.6 release doesn't support sending a message to multiple registration ids (or so I thought looking at 5e51375e57f2d013287208e88975ba772d95945e), but 0.7 has that. Is it possible to backport it to 0.6 so we can use that feature on stable?

**Comment by pimeys** [comment]
PR would be welcome.

Also 0.7 will stabilize this week after hyper 0.13 is out.

**Comment by SnowyCoder** [comment]
I'm not confident enough in this codebase (nor in my rust knowledge) to make a PR and I can totally wait some days, thanks for the quick response and for the lib!

**Comment by pimeys** [comment]
Sorry, but I need to ask why on earth you need the old futures 0.1 version of fcm? The whole ecosystem moves really fast now to the async/await syntax and it's much easier to understand if you're a rust beginner...

**Comment by SnowyCoder** [comment]
I don't really "need" the old version, but the new version isn't in crates.io yet.
Also I need to use actix-web that is still being ported so I'm always working with both the old and the new futures system.

**Comment by pimeys** [comment]
It is actually on crates.io! https://crates.io/crates/fcm/0.7.0-alpha.4

Stable version expected very soon, when hyper is done.

**Comment by pimeys** [comment]
And it is a high priority :) https://github.com/hyperium/hyper/issues/2025#issuecomment-560532807

**Comment by SnowyCoder** [comment]
Oh, It gave errors in cargo.toml and I assumed that it was too new to be in crates.io, I'm really sorry for the trouble :sweat_smile:

**Comment by pimeys** [comment]
Ah it will probably not work with rust versions older than 1.39.0! :) And it needs the whole codebase to work with tokio 0.2/futures 0.3. Or you must use the compat layer from the futures 0.3 to map the fcm requesting to the older futures format.

I'm currently seeing what I could do to backport this feature. Hoping a simple cherry-pick would do, so you could at least try it out!

**Comment by pimeys** [comment]
Could you try the [v0.6](https://github.com/panicbit/fcm-rust/tree/v0.6) branch from git if you get the multi-messages working? Just cherry-picked the code from master and at least it compiles :)

**Comment by pimeys** [comment]
If it works I'll release a new 0.6 version.

**Comment by SnowyCoder** [comment]
I can't test it now (I'm from mobile), tomorrow I'll try, thanks!

**Comment by SnowyCoder** [comment]
I've tested it, works perfectly

**Comment by pimeys** [comment]
Released 0.6.1.

You should consider moving to futures 0.3 and tokio 0.2 though at some point. It's so much simpler and nicer to use than the old interface :)

**Comment by SnowyCoder** [comment]
Thanks a lot! I'm already planning to migrate, just waiting for the main libs to be ported (ex. actix-web).
